# Generated by Django 4.2.9 on 2025-06-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('normal', '通常'), ('daily', '日次'), ('weekly', '週次'), ('monthly', '月次')], max_length=10)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10)),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('repeat_rule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
